name: build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.17.x
          - 1.18.x
          - 1.19.x
          - 1.20.x
        os:
          - ubuntu-latest
          - macos-12
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.5"
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Test and build package
        run: rake --trace build

      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest' && matrix.go == '1.20.x'
        uses: codecov/codecov-action@v3
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          # fail_ci_if_error: true
          verbose: true
          flags: unittests
          file: build/go-test-coverage.txt

      - name: Archive action artifacts
        if: always() # Always run step even if other steps fail
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.go }}
          path: |
            build/*
